<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250603161759 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP id_producto
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP id_supermercado
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER precio TYPE INT
        SQL);    
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER marca TYPE VARCHAR(100)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER marca SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos RENAME COLUMN id_categoria TO categoria_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ADD CONSTRAINT FK_767490E63397707A FOREIGN KEY (categoria_id) REFERENCES categorias (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_767490E63397707A ON productos (categoria_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id SET DEFAULT supermercados_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE supermercados ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP CONSTRAINT FK_23C0A40E7645698E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP CONSTRAINT FK_23C0A40E31EC9F0F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ADD id_producto INT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ADD id_supermercado INT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP producto_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios DROP supermercado_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id SET DEFAULT precios_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ALTER precio TYPE NUMERIC(10, 2)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ADD CONSTRAINT precios_id_supermercado_fkey FOREIGN KEY (id_supermercado) REFERENCES supermercados (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE precios ADD CONSTRAINT precios_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES productos (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos DROP CONSTRAINT FK_767490E63397707A
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_767490E63397707A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id TYPE INT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id SET DEFAULT productos_id_seq
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER id DROP IDENTITY
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER marca TYPE VARCHAR(100)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos ALTER marca DROP NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE productos RENAME COLUMN categoria_id TO id_categoria
        SQL);
    }
}
